### ISSUE TITLE
Checklist of logs in runner

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-java#282]
Runner should log 
- [ ] when runner started
- [ ] when it accepts gauge connections along with ports, 
- [ ] when step registry cache is loaded, how many steps, hooks it found, 
- [ ] when datastore init is completed and refreshed, 
- [ ] if custom screenshot function or other custom interfaces or parsers etc are implemented, - [ ] should log if it finds a fatal error and is about to quit, 
- [ ] when kill request is read by plugin, 
- [ ] if parsing/run of a file failed 
- [ ] if any environment variables that change the behaviour of the plugin is set to other than default, 
- [ ] unknown proto message is received by the plugin or if unable to unmarshal the proto message.
